version: '3'

services:
  api:
    build:
      context:
        environment:
          RELAY_HOST: api
          RELAY_PORT: 8000       
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  database:
  # how to build this?
    build: 